version: 4.11.{build}
skip_tags: true
os: Visual Studio 2015
#os: MinGW
#os: Default Azure
#build:
#  verbosity: minimal
# there's no 32bit installer
platform:
  - x64
  - x86
environment:
  matrix:
    - STRAWBERRY: 1
    - MSVC_CPERL: 1
matrix:
  allow_failures:
    - MSVC_CPERL: 1
clone_depth: 1
init:
  - git config --global core.autocrlf input
  # Disable popups as they hang the build as there is nobody to click on the OK button...
  # Hanging the build is a lot less user friendly than reporting a build failure.
  #
  # Disable of system hard error popup
  # See: https://msdn.microsoft.com/en-us/library/bb513638%28VS.85%29.aspx
  - reg add "HKLM\SYSTEM\CurrentControlSet\Control\Windows" /f /v ErrorMode /d 2
  # Disable the following popup on program failure:
  #     |       ** <program name> has stopped working **        |
  #     | Windows can check online for a solution to the problem|
  #     |  - Check online for a solution and close the program  |
  #     |  - Close the program                                  |
  # See: https://msdn.microsoft.com/en-us/library/bb513638%28VS.85%29.aspx
  - reg add "HKLM\Software\Microsoft\Windows\Windows Error Reporting" /f /v DontShowUI /d 1  
  #- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - set BITS=64
  - if "%PLATFORM%" == "x86" set BITS=32
  - if "%STRAWBERRY%" == "1" cinst strawberryperl -i
  - if "%MSVC_CPERL%" == "1" cinst -y curl
  - if "%MSVC_CPERL%" == "1" curl -O https://github.com/perl11/cperl/releases/download/cperl-5.26.0/cperl-5.26.0-win%BITS%.exe
  - if "%MSVC_CPERL%" == "1" .\cperl-5.26.0-win%BITS%.exe -y -o"C:\"

build: off

test_script:
  - 't\appveyor-test.bat'
